// Objective-C API for talking to github.com/unboundtech/DXcore-empty/DXcore/Ios Go package.
//   gobind -lang=objc github.com/unboundtech/DXcore-empty/DXcore/Ios
//
// File is generated by gobind. Do not edit.

#ifndef __Ios_H__
#define __Ios_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol IosProgressListener;
@class IosProgressListener;

@protocol IosProgressListener <NSObject>
- (void)onProgress:(NSString* _Nullable)msg;
@end

FOUNDATION_EXPORT NSString* _Nonnull IosGetFlag(void);

FOUNDATION_EXPORT NSString* _Nonnull IosGetFlowLine(void);

FOUNDATION_EXPORT void IosLog(NSString* _Nullable message);

FOUNDATION_EXPORT long IosMeasurePing(void);

FOUNDATION_EXPORT void IosSetAsnName(void);

FOUNDATION_EXPORT BOOL IosSetTimeZone(float timeDiff);

FOUNDATION_EXPORT void IosStartVPN(NSString* _Nullable cacheDir, NSString* _Nullable flowLine, NSString* _Nullable pattern);

FOUNDATION_EXPORT BOOL IosStop(void);

FOUNDATION_EXPORT BOOL IosStopVPN(void);

@class IosProgressListener;

@interface IosProgressListener : NSObject <goSeqRefInterface, IosProgressListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onProgress:(NSString* _Nullable)msg;
@end

#endif
